Transporter
Programming-TRIGON/RobotCodeOffSeason2022 pull request #1
Opened 2022-09-07 16:41 UTC by shay124578

2022-09-08 10:35 UTC, laviRZ requested changes
Format the code before committing

2022-09-08 10:35 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/Transporter.java
> +
extra newlines

2022-09-08 10:35 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/Transporter.java
> +    private final WPI_TalonSRX motor;
missing newline

2022-09-08 10:35 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/Transporter.java
> +    }
missing newline

2022-09-08 10:35 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/Transporter.java
> +    }
missing newline

2022-09-08 10:35 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/Transporter.java
> +    }
missing newline

2022-09-08 10:35 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/Transporter.java
> +
extra newlines

2022-09-08 10:35 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/TransporterConstants.java
> +    }
missing newline

2022-09-08 10:35 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/TransporterConstants.java
> +    protected static final double VOLTAGE_COMPENSATION = 10.5;
missing newline

2022-09-08 10:35 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/TransporterConstants.java
> +    protected static final double VOLTAGE_COMPENSATION = 10.5;
drop the protected

2022-09-08 10:35 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/TransporterConstants.java
> +        EJECT_VOLTAGE = -300;
voltage should be between `VOLTAGE_COMPENSATION` AND `-VOLTAGE_COMPENSATION`

2022-09-08 10:35 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/TransporterConstants.java
> +
extra newline

2022-09-08 10:35 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/TransporterConstants.java
> +        final double voltage;
missing newline

2022-09-08 10:35 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/TransporterConstants.java
> +    protected static final WPI_TalonSRX MOTOR = new WPI_TalonSRX(MOTOR_ID);
should be last

2022-09-14 12:55 UTC, laviRZ requested changes
reformat your code before committing

2022-09-14 12:55 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/Transporter.java
> +    private TransporterConstants.TransporterState currentState;
Move to the bottom of the variables

2022-09-14 12:55 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/Transporter.java
> +    }
should be the top function

2022-09-14 12:55 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/Transporter.java
> +    public void setState(TransporterConstants.TransporterState state) {
static import

2022-09-14 12:55 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/Transporter.java
> +        motor.set(ControlMode.PercentOutput, state.voltage / TransporterConstants.VOLTAGE_COMPENSATION);
make a function in utilities.Conversions called `voltageToCompensatedPower` to do this calculation

2022-09-14 12:55 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/Transporter.java
> +    }
get before set

2022-09-14 12:55 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/TransporterConstants.java
> +    protected static final WPI_TalonSRX MOTOR = new WPI_TalonSRX(MOTOR_ID);
default access, not protected

2022-09-14 12:55 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/TransporterConstants.java
> +        OFF(0);
missing newline

2022-09-14 12:55 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/TransporterConstants.java
> +    static final double VOLTAGE_COMPENSATION = 10.5;
should be on top

2022-09-16 06:17 UTC, laviRZ requested changes

2022-09-16 06:17 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/Transporter.java
> +                ControlMode.PercentOutput, Conversions.voltageToCompensatedPower(state.voltage, VOLTAGE_COMPENSATION));
move to a separate line

2022-09-16 06:17 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/TransporterConstants.java
> +    static final double VOLTAGE_COMPENSATION = 10.5;
rename to voltage compensation saturation

2022-09-16 06:17 UTC, laviRZ commented on src/main/java/frc/trigon/robot/utilities/Conversions.java
> +    public static double voltageToCompensatedPower(double currentVoltage, double voltageCompensation) {
rename to voltage compensation saturation

2022-09-16 06:29 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/Transporter.java
> +        motor = TransporterConstants.MOTOR;
move to decleration

2022-09-20 16:04 UTC, laviRZ requested changes

2022-09-20 16:04 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/Transporter.java
> +
extra newline

2022-09-20 16:04 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/Transporter.java
> +     * @return currentState
unwritten doc

2022-09-20 16:04 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/Transporter.java
> +     * Set the motor power
it sets the state, not the power

2022-09-20 16:04 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/Transporter.java
> +     * @param state TransporterState
what?

2022-09-20 17:15 UTC, shay124578 commented on src/main/java/frc/trigon/robot/subsystems/transporter/Transporter.java
> +     * @return currentState
Yishai told me to write there nothing

2022-09-20 17:27 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/Transporter.java
> +     * @return currentState
Then I'm telling you to

2022-09-21 15:27 UTC, lycaon7 requested changes, later dismissed

2022-09-21 15:27 UTC, lycaon7 commented on src/main/java/frc/trigon/robot/subsystems/transporter/Transporter.java
> +    public static Transporter getInstance() {
Add Java docs

2022-09-22 12:43 UTC, laviRZ requested changes

2022-09-22 12:43 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/Transporter.java
> +     * @return the current state of the transporterState
the current state of the transporterState?

2022-09-22 12:43 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/Transporter.java
> +     * Set the motor state.
doesn't set the motor state

2022-09-22 12:43 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/Transporter.java
> +        motor.set(state.power);
voltage compensation

2022-09-22 12:43 UTC, laviRZ commented on src/main/java/frc/trigon/robot/subsystems/transporter/TransporterConstants.java
> +        MOTOR.setInverted(MOTOR_INVERTED);
voltage compensation

2022-09-22 15:03 UTC, laviRZ approved these changes

2022-09-22 15:04 UTC, merged